#+HTML: <div align="center">
* Project Orion: Container
#+HTML: <img alt="GitHub" src="https://img.shields.io/github/license/EngineOrion/container">
#+HTML: </div>

#+end_center
* Intruction
Container is an essential part of the =Engine: Orion= project. It is
responsible of processing traffic. For control by the programmer, it
has to be programed in it's lisp-like programming language
NET-Script. This approach should allow the programmer to spend less
time configuring and programing the back-end.

But it can also be used as a stand alone interpreter, that executes
files. It can also be used in a shell like environment.

* Compile it
First you have to clone this repository. You must have the rust
toolchain installed.

If you wan't to run the tests, just type this command and all tests
will be run.

#+begin_src sh
$ cargo test --no-fail-fast
#+end_src

The complete build process can be done with this command:

#+begin_src sh
$ cargo build --release
   Compiling arrow v0.1.0 (C:\...\arrow)
    Finished release [optimized] target(s) in 1.06s
#+end_src

Now, you can execute the program with the following command:

#+begin_src sh
$ ./target/release/container repl
> 
#+end_src

* Documentation
The documentation can be generated by the rust toolchain. For that
just call:

#+begin_src sh
$ cargo doc --open
#+end_src
