#+HTML: <div align="center">
* Arrow
#+HTML: <img alt="GitHub" src="https://img.shields.io/github/license/EngineOrion/container">
#+HTML: </div>

#+end_center
* Intruction
Arrow is an essential part of the =Engine: Orion= project. It is
responsible of processing traffic. The syntax of arrow is very similar
to lisp. This approach should allow the programmer to spend less
time configuring and programing the back-end.

But it can also be used as a stand alone interpreter in a shell like environment.

* Compile it
First you have to clone this repository. You must have the rust
toolchain installed.

If you wan't to run the tests, just type this command and all tests
will be run.

#+begin_src sh
$ cargo test 
#+end_src

The complete build process can be done with this command:

#+begin_src sh
$ cargo build --release
   Compiling arrow v0.1.0 (C:\...\arrow)
    Finished release [optimized] target(s) in 1.06s
#+end_src

Now, you can execute the program with the following command:

#+begin_src sh
$ ./target/release/arrow
> 
#+end_src

* Run it
Now that the repl is compiled, the repl can be used to create evaluate
code. If the input isn't a function, it will execute immediately. If
it's a function, it must be called. The function can be called through
its symbol.

#+begin_src sh
$ ./target/release/arrow
Arrow: A LISP dialect.
Version: 0.1.0
> (* 5 5)
25
> (defun 'ret [] (return 5))
> 'ret
5
> (defun 'greet [] (print "hello"))
> 'greet
"hello"
nil
#+end_src

* Documentation
The documentation can be generated by the rust toolchain. For that
just call:

#+begin_src sh
$ cargo doc --open
#+end_src
